

# THIS IS THE CONFIGURATION FILE, WHERE YOU CAN FEED THE UPCOMING ANALYSIS WITH PARAMETERS OF YOUR CHOICE, BY CHANGING THE GIVEN DEFAULT VALUES
# EACH PARAMETER MAY BE PRECEDED BY A BRIEF DESCRIPTION AND THE TYPE OF VARIABLE YOU SHOULD PROVIDE, IF NECESSARY
# LEAVE EMPTY " " FOR NO INPUT


Core_Power: "20" #Your maximum number of available cores (str)


# ***IMPORTANT RAW DATA INSTRUCTIONS*** PLEASE READ CAREFULLY BEFORE PROCEEDING!
# 1. Your data should follow the fastq format
# 2. Concatenate your long-reads samples a priori if you have more than one files
# 3. Make sure that your forward and reverse fastq files of a sample have the exact same names, and the "R1" and "R2" reference strings in their ends accordingly, if you also have short pair-end reads
     #e.g.: Sample_01_R1.fastq (forward), Sample_01_R2.fastq (reverse)

Ldatadir: "raw_data/FastqFiles/MinION" #The dir containing your long raw data (type:str)
Short_Reads: "n" # Will you use short reads for the build of your assembly? (str,"y"|"n") If "y", please fill the ABOUT SHORT READS section below. If "n", please provide an estimation below.
GSE: "0.5g" #Genome Size Estimation, mandatory if you are not going to use short reads in your analysis. In g.


#ABOUT SHORT READS
Sdatadir: " " #The dir containing your short raw data (type:str)

#TRIMMOMATIC
MINLEN: "" # Drop the read if it is below a specified length
SLIDINGWINDOW: "" # Performs a sliding window trimming approach.
LEADING: "" # Cut bases off the start of a read, if below a threshold quality  
TRAILING: "" # Cut bases off the end of a read, if below a threshold quality  
AVGQUAL: "" # Drop the read if the average quality is below the specified level


#ABOUT LONG READS

#BUSCO
#*** PLEASE use only v3 datasets for running busco, which you can find  here: https://busco-archive.ezlab.org/v3/
LINEAGE: "actinopterygii_odb9" #write the name of the dataset with lower case along with its od$
SP: "zebrafish" #the model organism for busco (str)
ITER: "2" #Iterations of Racon Polishing (str)



